### ISSUE TITLE
methods called before insertCoin callback should error out

### ISSUE THREAD

**Issue by asadm** [asadm/playroom-unity#12]
I shouldn't be allowed to do:

```csharp
PlayroomKit.InsertCoin(() => {})
PlayroomKit.SetState(...)
```

All methods that are called before playroom has initialized should fail.

**Comment by momintlh** [comment]
Currently we are only logging the error. by fail do you mean to crash / stop execution if InsertCoin is not initialized?

**Comment by momintlh** [comment]
> Currently we are only logging the error. by fail do you mean to crash / stop execution if InsertCoin is not initialized?



> I shouldn't be allowed to do:
> 
> ```cs
> PlayroomKit.InsertCoin(() => {})
> PlayroomKit.SetState(...)
> ```
> 
> All methods that are called before playroom has initialized should fail.

**Comment by asadm** [comment]
logging error is fine

**Comment by asadm** [comment]
Does it print error in console in mock mode too?
