### ISSUE TITLE
Support setState and getState of Vector2, Vector3 and Quaternion

### ISSUE THREAD

**Issue by asadm** [asadm/playroom-unity#20]
I should be able to `SetState("pos", new Vector3(3.3f, 4.0f, 5.0f));` in both global and player states.

Also, trim all x,y,z and x,y,z,w floats to 4 decimals so they dont consume too much network bandwidth to transmit ie:
```cs
string floatToString(float f){
  return f.ToString("0.000");
}
```

**Comment by asadm** [comment]
Actually on a second thought, I think we can put these snippets in docs instead of core API.

**Comment by SaadBazaz** [comment]
Yes we'll add snippets in docs, but we also need to add overloads for intellisense. On 11 Sep 2023 09:05, Asad Memon ***@***.***> wrote:
Actually on a second thought, I think we can put these snippets in docs instead of core API.

**Comment by SaadBazaz** [comment]
We can add the trimming in docs, but for Vector etc we should add an overload func so that intellisense can work.

**Comment by asadm** [comment]
No let's keep API as-is and provide these helper snippets (to serialize Vector3 to string) in docs. I will do it.

**Comment by SaadBazaz** [comment]
Makes sense, will be consistent with other SDKs.

**Comment by SaadBazaz** [comment]
Closing this as marked as completed by #36 . Feel free to reopen otherwise.
