### ISSUE TITLE
Update unity API

### ISSUE THREAD

**Issue by asadm** [asadm/playroom-unity#22]
- [x] insertCoin signature to be changed to insertCoin(options, callback)
- [x] InitOptions updates: avatars, roomCode, skipLobby, reconnectGracePeriod, maxPlayersPerRoom
- [x] getRoomCode()
- [x] onDisconnect(callback)
- [x] waitForState()
- [x] waitForPlayerState()
- [x] Player.kick()

**Comment by asadm** [comment]
- [ ] onDisconnectCallback in insertCoin
- [ ] `defaultStates` and `defaultPlayerStates` in insertCoin
- [ ] Add `waitForPlayerState` in Playroom (current one is inside player state (do not remove it for now)
- [ ] `resetStates` and `resetPlayersStates` methods

**Comment by momintlh** [comment]
Closing this issue, changes in PR #31
