### ISSUE TITLE
Enable cross-origin for local testing

### ISSUE THREAD

**Issue by franciscoraposo** [asadm/playroom-unity#25]
I was having issues when trying to test the builds locally, as the remote scripts from unpkg.com were being blocked by the network.

I managed to fix it by changing the file `Assets\Plugins\PlayroomPlugin.jslib`

I added the following line in between lines 14 and 15:

`script.crossOrigin = 'anonymous';`

**Comment by SaadBazaz** [comment]
Was any other origin blocked too?
