### ISSUE TITLE
Unable to set boolean-type state variables

### ISSUE THREAD

**Issue by franciscoraposo** [asadm/playroom-unity#26]
When I try to do `SetState(NAME, true)` nothing seems to happen, so `GetState<bool>()` will never return the new value. I had to resort to making it an integer value instead.

I haven't delved enough into the code to understand what's the possible cause

**Comment by momintlh** [comment]
I just tested this, and it is working fine on my end. You do need to provide the same key when getting a state.
```C#
SetState("Name", true);
GetState<bool>("Name");
```

**Comment by momintlh** [comment]
Tested and working in #32, in case the issue persists open another issue!
