### ISSUE TITLE
Input on lobby not working in sample project

### ISSUE THREAD

**Issue by asadm** [asadm/playroom-unity#27]
In the demo project: https://docs.joinplayroom.com/demos/unity/index.html

The unity Input system is capturing the keystrokes and not sending them to input box. Can we fix this by not starting input capture on unity until insertCoin callback is called, in example project.

**Comment by momintlh** [comment]
Adding `WebGLInput.captureAllKeyboardInput = false;` before InsertCoin() and 
setting it to true in the callback fixes this.

**Comment by asadm** [comment]
can we add it to sdk itself if skipLobby is not set.
