### ISSUE TITLE
insertCoin's onDisconnect callback is wrong

### ISSUE THREAD

**Issue by asadm** [asadm/playroom-unity#33]
It's listening to onDisconnect(callback) instead of passing the callback to insertCoin itself ([see here](https://docs.joinplayroom.com/apidocs#insertcoin-initoptions--onlaunchcallback-ondisconnectcallback))

instead of .then .catch here, just use the right callbacks `onLaunchCallback` and `onDisconnectCallback`

https://github.com/asadm/playroom-unity/blob/aa3418e1125ae9accd48811aa2e81381422637f1/Assets/Plugins/PlayroomPlugin.jslib#L59

**Comment by asadm** [comment]
The signature for InsertCoin is ordered wrong?
https://github.com/asadm/playroom-unity/blob/aa3418e1125ae9accd48811aa2e81381422637f1/Assets/PlayroomKit/PlayroomKit.cs#L58

it should be similar to how js version is.

**Comment by momintlh** [comment]
@asadm pushed fixes in #35.
