### ISSUE TITLE
Errors piping to c#

### ISSUE THREAD

**Issue by asadm** [asadm/playroom-unity#38]
I noticed that if Unity calls some native javascript code, and that throws an error, the error doesn't propagate automatically in my C# code, so I can't wrap my own code in some try catch.
How do you guys deal with this situation?

![image](https://github.com/asadm/playroom-unity/assets/1973513/7e1f157e-c78c-4ff4-b664-ac3eb644252b)

**Comment by momintlh** [comment]
What should I do here catch the errors on JS side and send to unity?

**Comment by SaadBazaz** [comment]
> What should I do here, catch the errors on JS side and send to unity?

That sounds reasonable. Essentially it might be cool to differentiate between a Unity error and a JavaScript error.
So an interesting idea would be to throw an Error in C# with 
```json
{
    "type": "JAVASCRIPT_ERROR",
    "message": "Uncaught error in JavaScript library",
    "error": "<dump everything here/>"
}
```

**Comment by SaadBazaz** [comment]
Shifted to #40 for further discussion, as the OP's Issue has been solved.
