### ISSUE TITLE
InitOptions bug

### ISSUE THREAD

**Issue by asadm** [asadm/playroom-unity#44]
In `PlayroomKit.InitOptions`, i'm setting `maxPlayersPerRoom` to 2. But, up to four is still able to join lobby.

**Comment by SaadBazaz** [comment]
@asadm If possible, please link the Chat.

---

We gotta reproduce this.

This could be because of the nullable property (even though we need it) here:
https://github.com/asadm/playroom-unity/blob/main/Assets/PlayroomKit/PlayroomKit.cs#L42

This is how the options are being converted:
https://github.com/asadm/playroom-unity/blob/main/Assets/Plugins/PlayroomPlugin.jslib#L35

Maybe we're losing information somewhere in the middle? @momintlh 

Can we test this out (print logs?) and see?

**Comment by momintlh** [comment]
> @asadm If possible, please link the Chat.
> 
> We gotta reproduce this.
> 
> This could be because of the nullable property (even though we need it) here: https://github.com/asadm/playroom-unity/blob/main/Assets/PlayroomKit/PlayroomKit.cs#L42
> 
> This is how the options are being converted: https://github.com/asadm/playroom-unity/blob/main/Assets/Plugins/PlayroomPlugin.jslib#L35
> 
> Maybe we're losing information somewhere in the middle? @momintlh
> 
> Can we test this out (print logs?) and see?

I'll do some tests.

**Comment by asadm** [comment]
https://discord.com/channels/997752993598419044/1128151935669764096/1203515785331347457

**Comment by momintlh** [comment]
I just did a build test with setting `maxPlayersPerRoom = 2,` and this is the JSON coming from C# to JS: 
![image](https://github.com/asadm/playroom-unity/assets/77355191/a788316e-56de-4cea-9838-bd1700e8b328)

### My InsertCoin:
```C#
PlayroomKit.InsertCoin(new PlayroomKit.InitOptions()
        {
            maxPlayersPerRoom = 2,
            defaultPlayerStates = new() {
                        {"score", -500},
                    }
        }, () =>
        {
            PlayroomKit.OnPlayerJoin(AddPlayer);
            PlayroomKit.SetState("score", score);
        });
```

and Only 2 players can join:
### P1
![image](https://github.com/asadm/playroom-unity/assets/77355191/92352005-fca5-488c-aa15-2e0936084e46)
 
### P2
![image](https://github.com/asadm/playroom-unity/assets/77355191/4adce3ee-9662-4b66-bd89-580fee423d62)

and P3:
![image](https://github.com/asadm/playroom-unity/assets/77355191/c95e9aec-1ae8-4d1f-9776-157cc240c251)

@asadm @SaadBazaz

**Comment by SaadBazaz** [comment]
<img width="778" alt="Screenshot 2024-02-04 at 19 26 11" src="https://github.com/asadm/playroom-unity/assets/51885228/33ff685a-a3e2-43dc-9028-14891abafb35">

@asadm - I noticed that our latest release is 3 weeks ago, despite merges and updates in the middle. Do you think this is the reason?

We may need to add a tag to our next PR to trigger it. Should we add one in #43?

**Comment by asadm** [comment]
is our current main stable? i can do a release once we are stable.

**Comment by SaadBazaz** [comment]
@momintlh Test the current main. Don't add RPC to it yet; that can cause instability for now.

**Comment by momintlh** [comment]
I tested the latest release and had no issues with setting maxPlayersPerRoom = 2.
3rd Player:
![image](https://github.com/asadm/playroom-unity/assets/77355191/78dad2c5-1003-4494-aa15-60d77b1090d8)

**Comment by momintlh** [comment]
The issue ended-up being that options parameter was not passed to InsertCoin(). 

In v0.0.10 the signature is:
```InsertCoin(callback, options)```
