### ISSUE TITLE
mock mode differences from real web mode

### ISSUE THREAD

**Issue by asadm** [asadm/playroom-unity#47]
https://discord.com/channels/997752993598419044/1224804678089445386/1224804678089445386

**Comment by momintlh** [comment]
The OnPlayerJoin change was due to only 1 player being allowed during MockMode, I guess for this issuse we just need to call the `OnPlayerJoinWrapperCallback` within mockmode as well.

**Comment by SaadBazaz** [comment]
> The OnPlayerJoin change was due to only 1 player being allowed during MockMode, I guess for this issuse we just need to call the `OnPlayerJoinWrapperCallback` within mockmode as well.

How would that resolve the `Kick` issue? What is your understanding of that problem?

**Comment by momintlh** [comment]
> > The OnPlayerJoin change was due to only 1 player being allowed during MockMode, I guess for this issuse we just need to call the `OnPlayerJoinWrapperCallback` within mockmode as well.
> 
> How would that resolve the `Kick` issue? What is your understanding of that problem?

Kick() was never implemented in MockMode before.
Considering the player in mock mode is a host, we just need to remove / destroy that player object? I think we might need to introduce 2 players within mockmode : 1 host and another non-host, to accurately simulate `Kick()` as the web version. .

**Comment by SaadBazaz** [comment]
> Kick() was never implemented in MockMode before. Considering the player in mock mode is a host, we just need to remove / destroy that player object? I think we might need to introduce 2 players within mockmode : 1 host and another non-host, to accurately simulate `Kick()` as the web version.

I agree, that would allow the developer to test more usecases. How would the second user work, though? Would it mirror everything player1 does?

**Comment by momintlh** [comment]
> > Kick() was never implemented in MockMode before. Considering the player in mock mode is a host, we just need to remove / destroy that player object? I think we might need to introduce 2 players within mockmode : 1 host and another non-host, to accurately simulate `Kick()` as the web version.
> 
> I agree, that would allow the developer to test more usecases. How would the second user work, though? Would it mirror everything player1 does?

We can disable input for the second player.

**Comment by SaadBazaz** [comment]
Kick Issue is solved.

@momintlh have we solved this in #50 ?
<img width="1069" alt="Screenshot 2024-04-14 at 23 28 41" src="https://github.com/asadm/playroom-unity/assets/51885228/18a5c7e5-d107-437b-ae98-7ec9ee1055a7">

**Comment by momintlh** [comment]
> Kick Issue is solved.
> 
> @momintlh have we solved this in #50 ? <img alt="Screenshot 2024-04-14 at 23 28 41" width="1069" src="https://private-user-images.githubusercontent.com/51885228/322295074-18a5c7e5-d107-437b-ae98-7ec9ee1055a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMTk4MTYsIm5iZiI6MTcxMzExOTUxNiwicGF0aCI6Ii81MTg4NTIyOC8zMjIyOTUwNzQtMThhNWM3ZTUtZDEwNy00MzdiLWFlOTgtN2VjOWVlMTA1NWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDE4MzE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkODg5M2UyYzU2MzM1YTAxYWY4Y2Q5YTUxNzA3MTk2MzE3ZWExNjQ4ZGRlNjQyYjQ4MjA2MTg4NDMzMThlM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hF8Y6yDoSl5Rt7jzJkfd9u0MwfjbfX3n9RmHm4l9sn8">

![image](https://github.com/asadm/playroom-unity/assets/77355191/6ccda6a7-9e95-4557-b0bd-ca6529ed593a)

From #50 ^

**Comment by SaadBazaz** [comment]
Just in case, we should scan the code to see if we've left some mistakes/inconsistencies like this anywhere else.
