### ISSUE TITLE
Build fails due to missing functions

### ISSUE THREAD

**Issue by SaadBazaz** [asadm/playroom-unity#63]
### What happened?

Hi! 
Wasn't active this last week but got the chance of trying it today.

Build fails because some functions in `PlayroomKit.cs` call native functions that don't exist in `PlayroomPlugin.jslib`
like `UnsubscribeOnPlayerJoinInternal` and `UnsubscribeOnQuitInternal`

### Version

Unknown

### Link to original discussion

https://discord.com/channels/997752993598419044/1128151935669764096/1234894885820301323

**Comment by SaadBazaz** [comment]
@momintlh - Can you reproduce this?

**Comment by momintlh** [comment]
Did they try `npm run build` in Assets/playroomkit folder? I need to know the version as well.

**Comment by SaadBazaz** [comment]
To resolve such an issue, make sure you are building the jslib file:

In your project directory 
`cd .\Assets\PlayroomKit\` 

and run `npm run build`
