### ISSUE TITLE
Make all non-upstream functions private

### ISSUE THREAD

**Issue by SaadBazaz** [asadm/playroom-unity#72]
### What happened?

hey, I just figure out that there is a GetPlayerState in the Player class. How is it different from GetState?

## Possible solution
Any function which isn't in PlayroomKit JS SDK, should be private in Unity SDK. So we have complete feature parity.

### Version

0.0.22

### What is your environment?

Unknown

### Link to original discussion

https://discord.com/channels/997752993598419044/1128151935669764096/1240665682782453825
Related: https://discord.com/channels/997752993598419044/1128151935669764096/1240729357513916416

### Relevant log output

![image](https://github.com/asadm/playroom-unity/assets/51885228/5fdc7177-ea31-4418-b1b8-a301b122d020)

**Comment by SaadBazaz** [comment]
You might also want to read this thread, @momintlh :
https://discord.com/channels/997752993598419044/1128151935669764096/1240729357513916416

This developer has a lot of good points. We can clean up our implementation better, and make the DX cleaner for developers.

Tagging #40 as it seems related.

**Comment by momintlh** [comment]
Will fix this today.

**Comment by SaadBazaz** [comment]
Solved in #73 , released in v0.0.23
