### ISSUE TITLE
[Feature-Request]: A central callback handling system

### ISSUE THREAD

**Issue by asadm** [asadm/playroom-unity#75]
### What do you want to see?

We keep adding more complexity by handling callback array for each feature individually. We also dont support multiple callbacks (as in js version) for many features like [WaitForState](https://github.com/asadm/playroom-unity/blob/a94ef0199a1051b199d22b70491eb909fdd4ce01/Assets/PlayroomKit/PlayroomKit.cs#L754) which just has one global callback holder?

Can we abstract away the callback system such that:

1. a callback handler is stored in a global dictionary against a random id
2. the id is the thing sent to jslib
3. the jslib sends data back along with callback id 
4. we retrieve the handler back from global dict and route to the right id.

**Comment by SaadBazaz** [comment]
Adds to #40

**Comment by SaadBazaz** [comment]
Resolved in #77 (initial implementation) and #80 (improvement for RPC)
