### ISSUE TITLE
.color in GetProfile() should return Color typed instance too

### ISSUE THREAD

**Issue by asadm** [asadm/playroom-unity#9]

**Comment by momintlh** [comment]
Is this what you are talking about?
### API:
![image](https://github.com/asadm/playroom-unity/assets/77355191/f474b02f-de50-4c2e-8e03-6c224e84253a)


### Usage:
![image](https://github.com/asadm/playroom-unity/assets/77355191/fbbfaab7-b1a0-4797-9119-a10eeb2322d2)

**Comment by asadm** [comment]
@momintlh I meant that GetProfile().color should return 'UnityEngine.Color' type. So that I can do:
`component.material.color = playerList[i].GetProfile().color`.
